# Generated by Django 4.2.4 on 2024-01-18 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionrow_producedrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producedrow',
            name='package',
        ),
        migrations.RemoveField(
            model_name='producedrow',
            name='packageQuantity',
        ),
        migrations.RemoveField(
            model_name='producedrow',
            name='quantityPerPackage',
        ),
    ]
