# Generated by Django 4.2.4 on 2024-01-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_remove_allocatematerial_pending'),
        ('sales', '0006_sales_order_status'),
        ('production', '0004_producedrow_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocatedMaterialProductionFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TotalCost', models.DecimalField(decimal_places=2, max_digits=50)),
                ('production_date', models.DateField(auto_now_add=True)),
                ('Material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_product', to='inventory.allocatematerial')),
            ],
        ),
        migrations.RemoveField(
            model_name='production',
            name='cutting',
        ),
        migrations.RemoveField(
            model_name='production',
            name='packing',
        ),
        migrations.RemoveField(
            model_name='production',
            name='printing',
        ),
        migrations.RemoveField(
            model_name='production',
            name='ready_to_dispatch',
        ),
        migrations.RemoveField(
            model_name='production',
            name='sales_order',
        ),
        migrations.RemoveField(
            model_name='production',
            name='stitching',
        ),
        migrations.AddField(
            model_name='production',
            name='productionUnit',
            field=models.CharField(default='Cutting', max_length=250),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductionRow',
        ),
        migrations.AddField(
            model_name='allocatedmaterialproductionflow',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_steps', to='production.production'),
        ),
        migrations.AddField(
            model_name='allocatedmaterialproductionflow',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales'),
        ),
    ]
