# Generated by Django 4.2.4 on 2024-01-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_allocatedmaterialproductionflow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatedmaterialproductionflow',
            name='production',
        ),
        migrations.AddField(
            model_name='allocatedmaterialproductionflow',
            name='cutting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allocatedmaterialproductionflow',
            name='cutting_unit',
            field=models.CharField(blank=True, choices=[('Unit 1', 'Unit 1'), ('Unit 2', 'Unit 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='allocatedmaterialproductionflow',
            name='packaginganddispatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allocatedmaterialproductionflow',
            name='printing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allocatedmaterialproductionflow',
            name='stitching',
            field=models.BooleanField(default=True),
        ),
    ]
