# Generated by Django 4.2.4 on 2024-01-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_allocatedmaterialproductionflow_production_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producedrow',
            name='TotalCost',
        ),
    ]
