# Generated by Django 4.2.4 on 2024-01-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_remove_producedrow_totalcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatedmaterialproductionflow',
            name='TotalCost',
        ),
        migrations.AddField(
            model_name='producedrow',
            name='TotalCost',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=50),
            preserve_default=False,
        ),
    ]
