# Generated by Django 4.2.4 on 2024-01-19 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sales_order_status'),
        ('production', '0008_remove_allocatedmaterialproductionflow_totalcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedmaterialproductionflow',
            name='rowItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.itemrow'),
            preserve_default=False,
        ),
    ]
