# Generated by Django 4.2.4 on 2024-01-19 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_allocatedmaterialproductionflow_rowitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatedmaterialproductionflow',
            name='rowItem',
        ),
    ]
