# Generated by Django 4.2.4 on 2024-01-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_remove_allocatedmaterialproductionflow_rowitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producedrow',
            name='TotalCost',
        ),
    ]
