# Generated by Django 4.2.4 on 2024-01-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_remove_producedrow_totalcost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producedrow',
            name='row_type',
        ),
    ]
