# Generated by Django 4.2.4 on 2024-01-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_remove_producedrow_row_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='producedrow',
            name='productionUnit',
            field=models.CharField(default='ss', max_length=250),
            preserve_default=False,
        ),
    ]
