# Generated by Django 4.2.4 on 2024-01-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_producedrow_productionunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='producedrow',
            name='alloca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.allocatedmaterialproductionflow'),
            preserve_default=False,
        ),
    ]
