# Generated by Django 4.2.4 on 2024-01-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_allocatedmaterialproductionflow_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatedmaterialproductionflow',
            name='last_update',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
