# Generated by Django 4.2.4 on 2024-01-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_allocatedmaterialproductionflow_cutting_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocatedmaterialproductionflow',
            old_name='last_update',
            new_name='last_update_cutting',
        ),
        migrations.AddField(
            model_name='allocatedmaterialproductionflow',
            name='last_update_printing',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allocatedmaterialproductionflow',
            name='last_update_stitching',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
