# Generated by Django 4.2.4 on 2024-01-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_rename_last_update_allocatedmaterialproductionflow_last_update_cutting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatedmaterialproductionflow',
            name='stitching_unit',
            field=models.CharField(blank=True, choices=[('Unit 1', 'Unit 1'), ('Unit 2', 'Unit 2')], max_length=20, null=True),
        ),
    ]
