# Generated by Django 4.2.4 on 2024-01-23 03:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sales_order_status'),
        ('inventory', '0025_allocatematerial_idx'),
        ('production', '0021_allocatedmaterialproductionflow_last_update_packaginganddispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyToDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_of_single', models.DecimalField(decimal_places=2, max_digits=50)),
                ('cost_of_all', models.DecimalField(decimal_places=2, max_digits=50)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=50)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.DateTimeField(choices=[('Pending', 'Pending'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched')], default='Pending')),
                ('alloca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.allocatedmaterialproductionflow')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_product', to='inventory.product')),
                ('product_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productstock')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales')),
            ],
        ),
    ]
