# Generated by Django 4.2.4 on 2024-01-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_readytodispatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readytodispatch',
            name='cost_of_all',
        ),
        migrations.AlterField(
            model_name='readytodispatch',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched')], default='Pending', max_length=250),
        ),
    ]
