# Generated by Django 4.2.4 on 2024-01-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_readytodispatch_ledt'),
    ]

    operations = [
        migrations.AddField(
            model_name='readytodispatch',
            name='disp_left',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
