# Generated by Django 4.2.4 on 2024-01-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_readytodispatch_disp_left'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatedmaterialproductionflow',
            name='last_update_packaginganddispatch',
        ),
        migrations.RemoveField(
            model_name='allocatedmaterialproductionflow',
            name='packaginganddispatch',
        ),
        migrations.RemoveField(
            model_name='allocatedmaterialproductionflow',
            name='packaginganddispatch_status',
        ),
    ]
