# Generated by Django 4.2.4 on 2023-12-23 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_materialstock_cost_of_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialstock',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstock',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
