# Generated by Django 4.2.4 on 2023-12-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_materialstock_total_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialstock',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productstock',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
            preserve_default=False,
        ),
    ]
