# Generated by Django 4.2.4 on 2023-12-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_productmaterial_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialstock',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sales', 'Sales')], default='purchase', max_length=10),
        ),
        migrations.AddField(
            model_name='productstock',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sales', 'Sales')], default='purchase', max_length=10),
        ),
    ]
