# Generated by Django 4.2.4 on 2023-12-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_materialstock_type_productstock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('return', 'Return')], default='purchase', max_length=10),
        ),
    ]
