# Generated by Django 4.2.4 on 2023-12-28 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_productstock_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('quantity_per_piece', models.IntegerField()),
                ('order_quantity', models.IntegerField()),
                ('required', models.IntegerField()),
                ('available', models.IntegerField()),
                ('allocated', models.IntegerField(default=0)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.material')),
            ],
        ),
    ]
