# Generated by Django 4.2.4 on 2023-12-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_allocatematerial_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocatematerial',
            name='material',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
