# Generated by Django 4.2.4 on 2024-01-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_materialstock_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialstock',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='materialstock',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='object_id',
        ),
    ]
