# Generated by Django 4.2.4 on 2024-01-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_materialstock_content_type_materialstock_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatematerial',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_of_measurement',
            field=models.CharField(choices=[('Piece', 'Piece'), ('Liter', 'Liter'), ('Meter', 'Meter'), ('Centimeter', 'Centimeter'), ('Yard', 'Yard'), ('Inch', 'Inch')], default='Piece', max_length=10),
        ),
    ]
