# Generated by Django 4.2.4 on 2024-01-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_allocatematerial_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatematerial',
            name='pending',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
