# Generated by Django 4.2.4 on 2024-01-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_allocatematerial_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatematerial',
            name='pending',
        ),
    ]
