# Generated by Django 4.2.4 on 2024-01-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_allocatematerial_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocatematerial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='allocatematerial',
            name='sales',
        ),
    ]
