# Generated by Django 4.2.4 on 2024-01-18 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_allocatematerial_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocatematerial',
            old_name='sales_order',
            new_name='sales',
        ),
    ]
