# Generated by Django 4.2.4 on 2024-01-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_rename_sales_order_allocatematerial_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocatematerial',
            old_name='Material',
            new_name='material',
        ),
    ]
