# Generated by Django 4.2.4 on 2024-01-19 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_allocatematerial_rowitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocatematerial',
            name='idx',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
