# Generated by Django 4.2.4 on 2024-01-23 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_joblist_material_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='received_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 30, 15, 14, 48, 403886)),
        ),
    ]
