# Generated by Django 4.2.4 on 2023-12-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Department_employee',
        ),
    ]
