# Generated by Django 4.2.4 on 2023-12-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0002_rename_department_department_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='pan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
