# Generated by Django 4.2.4 on 2023-12-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_department_name'),
        ('hrd', '0003_employee_email_employee_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.department'),
        ),
        migrations.DeleteModel(
            name='Department_employee',
        ),
    ]
