# Generated by Django 4.2.4 on 2023-12-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrd', '0004_alter_employee_department_delete_department_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='Work',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='work',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
