# Generated by Django 4.2.4 on 2023-12-23 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_materialstock_total_value_productstock_total_value'),
        ('accounting', '0011_rename_billing_address_purchaseinvoice_billingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitemrow',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='inventory.material'),
        ),
    ]
