# Generated by Django 4.2.4 on 2023-12-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_materialstock_total_value_productstock_total_value'),
        ('accounting', '0013_purchasereturn_purchasereturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_products', to='inventory.product'),
        ),
    ]
