# Generated by Django 4.2.4 on 2023-12-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_purchaseinvoice_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='balance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
