# Generated by Django 4.2.4 on 2023-12-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_purchaseinvoice_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='from_ledger',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to='accounting.ledger'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymententry',
            name='tax_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.ledger'),
        ),
        migrations.AddField(
            model_name='paymententry',
            name='to_ledger',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to='accounting.ledger'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PaymentEntryRow',
        ),
    ]
