# Generated by Django 4.2.4 on 2023-12-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_paymententry_from_ledger_paymententry_tax_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymententry',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='tax_ledger',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
    ]
