# Generated by Django 4.2.4 on 2023-12-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_companysettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasequotation',
            old_name='csgst_total',
            new_name='tax',
        ),
        migrations.RemoveField(
            model_name='purchasequotation',
            name='sgst_total',
        ),
    ]
