# Generated by Django 4.2.4 on 2023-12-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_rename_csgst_total_purchasequotation_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitemrow',
            name='taxPerproduct',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
