# Generated by Django 4.2.4 on 2023-12-27 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_productstock_type'),
        ('accounting', '0021_purchaseitemrow_taxperproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitemrow',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='inventory.service'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitemrow',
            name='taxPerPiece',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
