# Generated by Django 4.2.4 on 2023-12-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_quotation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=20, null=True),
        ),
    ]
