# Generated by Django 4.2.4 on 2023-12-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sales_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='balance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
